#include <stdio.h>

#include "date_formats.h"

char * formats_dictionary[MAX_FORMATS] = {
	CMD_ARG_TOKEN_DATE_FORMAT_DDMMYYYY,
	CMD_ARG_TOKEN_DATE_FORMAT_YYYYDDD,
	CMD_ARG_TOKEN_DATE_FORMAT_YYYYMMDD,
	CMD_ARG_TOKEN_DATE_FORMAT_YYYYMMDDHHMMSS,
	CMD_ARG_TOKEN_DATE_FORMAT_YYYYDDDHHMMSS
};