#ifndef DATE_FORMATS__H
#define DATE_FORMATS__H

#define MAX_FORMATS 5

#define CMD_ARG_TOKEN_DATE_FORMAT_DDMMYYYY "DDMMAAAA"
#define CMD_ARG_TOKEN_DATE_FORMAT_YYYYDDD "AAAADDD"
#define CMD_ARG_TOKEN_DATE_FORMAT_YYYYMMDD "AAAAMMDD"
#define CMD_ARG_TOKEN_DATE_FORMAT_YYYYMMDDHHMMSS "AAAAMMDDHHmmSS"
#define CMD_ARG_TOKEN_DATE_FORMAT_YYYYDDDHHMMSS "AAAADDDHHmmSS"

#endif