#ifndef TYPES__H
#define TYPES__H

#include <stdio.h>

/*****TIPOS*****/
typedef enum{
	OK = 0,
	ERR_INVALID_DATE_FORMAT,
	ERR_INVALID_INVOCATION,
	ERR_NULL_POINTER,
	ERR_SYSTEM_DATE,
	ERR_OUT_OF_MEMORY
}status_t;

typedef enum{
	DATE_FORMAT_DDMMYYYY,
	DATE_FORMAT_YYYYDDD,
	DATE_FORMAT_YYYYMMDD,
	DATE_FORMAT_YYYYMMDDHHmmSS,
	DATE_FORMAT_YYYYDDDHHmmSS
}date_format_t;

#endif